### ISSUE TITLE
Missing DLL/Requirement

### ISSUE THREAD

**Issue by ChrisHammond** [EngageSoftware/Engage-Survey#7]
With Engage Survey, it appears that the Module requires the AntiXss library from Microsoft, but this isn't made clear as a requirement upon installation. After installation, when trying to edit a survey this error will be thrown.

InnerException: Could not load file or assembly 'AntiXssLibrary, Version=4.2.0.0, Culture=neutral, PublicKeyToken=d127efab8a9c114f' or one of its dependencies. The system cannot find the file specified.

I'm not sure if the DLL can be distributed or not, but putting a dependency in the .DNN file might help to make people aware of the need before installation.

**Comment by bdukes** [comment]
What version of the module are you using?  The current version doesn't directly reference AntiXss, so I'm not sure if there's some indirect reference, or if this is from somewhere else.  Can you post the stack trace?

**Comment by ChrisHammond** [comment]
The client installed 3.5.1. 

I haven't seen the error myself, just what they provided to me as reported, and then after I deployed the DLL they said it was fixed. I'll see if I can recreate.

**Comment by bdukes** [comment]
Nevermind, I was looking at the wrong module.  It appears that AntiXss is declared in the manifest and included in the package…

**Comment by bdukes** [comment]
Which would lead me to believe that it was a version mismatch, but if your client reported that they didn't have it in the `bin` at all, that's rather mysterious

**Comment by ChrisHammond** [comment]
Well crap. Sorry about that. I'll see if I can recreate/track down the issue and open a new issue if I can find the cause.

**Comment by bdukes** [comment]
:+1:
